
import { NotebookStep } from '../types';

const createMarkdownCell = (source: string | string[]) => ({
  cell_type: 'markdown',
  metadata: {},
  source: Array.isArray(source) ? source.map(s => s.endsWith('\n') ? s : s + '\n') : [source],
});

const createCodeCell = (source: string | string[]) => ({
  cell_type: 'code',
  execution_count: null,
  metadata: {},
  outputs: [],
  source: Array.isArray(source) ? source.map(s => s.endsWith('\n') ? s : s + '\n') : [source],
});

/**
 * Generates the content for a .ipynb file from a series of notebook steps.
 * @param steps An array of NotebookStep objects representing the user's workflow.
 * @param dbName The name of the connected database.
 * @returns A JSON string representing the notebook file.
 */
export const generateIpynbContent = (steps: NotebookStep[], dbName?: string): string => {
  const introCell = createMarkdownCell([
    '# QueryPal Notebook\n\n',
    'This notebook was automatically generated by QueryPal. It contains a reproducible sequence of natural language prompts and their corresponding MongoDB queries.\n\n',
    '**Environment:** This notebook is configured for **Python** and uses the **PyMongo** library to interact with MongoDB.'
  ]);

  const setupCell = createCodeCell([
    '# 1. Install necessary libraries\n',
    '!pip install pymongo\n\n',
    '# 2. Set up the MongoDB connection\n',
    '# IMPORTANT: Replace with your actual connection string from Azure portal or your DB host.\n',
    'import pymongo\n',
    'from pprint import pprint\n\n',
    '# Example connection string format:\n',
    '# connection_string = "mongodb+srv://<user>:<password>@<cluster-uri>/<database>?retryWrites=true&w=majority"\n',
    'connection_string = "YOUR_CONNECTION_STRING_HERE"\n',
    'client = pymongo.MongoClient(connection_string)\n\n',
    '# 3. Select your database\n',
    `db = client['${dbName || 'your_database_name'}']\n\n`,
    'print("Setup complete. You can now run the query cells below.")'
  ]);

  const cells = steps.flatMap((step, index) => {
    const contextMarkdown = step.contextSource
      ? `This query used the output from **${step.contextSource}** as input.\n\n`
      : '';
      
    const promptCell = createMarkdownCell([
      `## Step ${index + 1}: User Prompt\n\n`,
      contextMarkdown,
      `> ${step.prompt}`
    ]);

    const pythonQuery = step.query;

    const queryCell = createCodeCell([
        `# Query for: "${step.prompt}"\n`,
        `cursor = ${pythonQuery}\n\n`,
        '# Iterate and print results (limited to 20 for display)\n',
        'results = list(cursor.limit(20))\n',
        'pprint(results)'
    ]);

    return [promptCell, queryCell];
  });

  const notebook = {
    cells: [introCell, setupCell, ...cells],
    metadata: {
      kernelspec: {
        display_name: 'Python 3 (ipykernel)',
        language: 'python',
        name: 'python3',
      },
      language_info: {
        name: 'python',
        version: '3.9',
        mimetype: 'text/x-python',
        file_extension: '.py'
      },
    },
    nbformat: 4,
    nbformat_minor: 5,
  };

  return JSON.stringify(notebook, null, 2);
};


/**
 * Triggers a browser download for the given content.
 * @param content The string content of the file.
 * @param filename The desired name for the downloaded file.
 * @param contentType The MIME type of the file.
 */
export const downloadFile = (content: string, filename: string, contentType: string) => {
    const blob = new Blob([content], { type: contentType });
    const link = document.createElement('a');
    
    link.href = URL.createObjectURL(blob);
    link.download = filename;
    
    document.body.appendChild(link);
    link.click();
    
    document.body.removeChild(link);
    URL.revokeObjectURL(link.href);
};